# Generated by Django 4.2.4 on 2023-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='post/%Y/%m/%d/', verbose_name='Изображение')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена')),
                ('orders', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Заказы')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
