# Generated by Django 4.2.4 on 2023-09-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_burgers_options_alter_burgers_name_pizza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burgers',
            new_name='Products',
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
