# Generated by Django 4.2.4 on 2023-09-02 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_options_remove_comment_author_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
