# Generated by Django 4.2.4 on 2023-09-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_order_items_remove_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
